### ISSUE TITLE
Admin/typo

### ISSUE THREAD

**Issue by cwlind** [joshsny/SpeedStore#6]
Great library, thank you for creating this and sharing! 
Just a small thing:   in the readme.md file, in the code for adding the library to the manifest, there is an extra comma at the end after 
"version": "6"**,**   <--- 

Could cause some people problems if they just copy/paste.

**Comment by joshsny** [comment]
Thanks for pointing this out, will fix it now :)

**Comment by joshsny** [comment]
All fixed, thanks again for pointing out the typo!
